repositories:
  - name: eks
    url: https://aws.github.io/eks-charts

releases:
  - name: fluent-bit
    namespace: kube-system
    chart: eks/aws-for-fluent-bit
    version: ~0.1.18
    installed: {{ eq (env "INSTALLED" | default "true") "true" | toYaml }}
    values:
      - values.yaml.gotmpl
      {{ if eq (env "USER_HELM_VALUES" | default "false") "true" }}
      - values.user.yaml.gotmpl
      {{ end }}